import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import AuthProvider from "./providers/auth-provider";

const gabarito = Gabarito({ subsets: ["latin"], variable: "--font-gabarito" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={cn("bg-background font-sans", gabarito.variable)}>
        <AuthProvider>
          <Providers>
            <Toaster />
            <div className="flex min-h-dvh">
              <div className="grow overflow-auto">{children}</div>
            </div>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
